# Generated by Django 3.2.2 on 2022-05-11 08:46

import app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, validators=[app.models.validate_name])),
                ('email', models.EmailField(max_length=70, unique=True, validators=[django.core.validators.EmailValidator()])),
                ('contact', models.BigIntegerField(unique=True, validators=[app.models.validate_contact])),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
