# Generated by Django 3.2.2 on 2022-05-13 10:29

import django.contrib.auth.password_validation
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockname', models.CharField(max_length=100)),
                ('stocktotalqty', models.IntegerField()),
                ('stockbaseqty', models.IntegerField()),
                ('barcode', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=200, validators=[django.contrib.auth.password_validation.validate_password]),
        ),
    ]
