# Generated by Django 3.2.2 on 2022-05-13 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220513_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.BigIntegerField(blank=True, unique=True),
        ),
    ]
