# Generated by Django 3.2.2 on 2022-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stock_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
