# Generated by Django 3.2.2 on 2022-05-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stock_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='barcode',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
